Add Consul Template template
TouchType/data-lake-adlstool pull request #1
Opened 2017-09-04 08:59 UTC by grahamsk

2017-09-04 09:00 UTC, grahamsk commented
Using this consul template file to configure a cred file for the tool in VSTS

2017-09-04 09:11 UTC, imcdnzl requested changes
As discussed, please add a new line at the end. Please also make a PR upstream

2017-09-04 09:53 UTC, imcdnzl approved these changes

2017-09-04 12:54 UTC, mvagias approved these changes

2017-09-12 07:08 UTC, imcdnzl approved these changes
LGTM

2017-11-02 16:17 UTC, merged